# Generated by Django 3.0.4 on 2020-03-23 18:39

from django.db import migrations, models
import peer_assessment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(default=peer_assessment.models.User.default_pwd, max_length=100)),
                ('eagle_id', models.CharField(max_length=8, unique=True, validators=[peer_assessment.models.User.validate_digit_length], verbose_name='id')),
                ('type', models.CharField(choices=[('S', 'Student'), ('I', 'Instructor'), ('T', 'TA'), ('A', 'Administrator')], max_length=1)),
            ],
        ),
    ]
