# Generated by Django 3.0.3 on 2020-04-17 04:40

from django.db import migrations, models
import peer_assessment.models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentOne',
            fields=[
                ('group_id', models.CharField(max_length=100)),
                ('assignment_id', models.CharField(max_length=100)),
                ('key_2', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_students', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupOne',
            fields=[
                ('eagle_id', models.CharField(max_length=8, validators=[peer_assessment.models.GroupOne.validate_digit_length], verbose_name='id')),
                ('key_1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='eagle_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[peer_assessment.models.User.validate_digit_length], verbose_name='id'),
        ),
    ]
