# Generated by Django 3.0.3 on 2020-04-18 07:27

from django.db import migrations, models
import django.db.models.deletion
import peer_assessment.models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=100, primary_key=100, serialize=False)),
                ('assignment_name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('completion', models.BooleanField()),
                ('qset_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('instructor_list_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eval_set',
            fields=[
                ('eval_set_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grader',
            fields=[
                ('grader_name', models.CharField(max_length=100)),
                ('grader_ass_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('aggregate_score', models.CharField(max_length=100)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assignment')),
                ('eval_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Eval_set')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_students', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='eagle_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[peer_assessment.models.User.validate_digit_length], verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='30562819', max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionOne',
            fields=[
                ('key_3', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('qset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assignment')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Question')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorSet',
            fields=[
                ('key_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('instructor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Instructors')),
                ('instructor_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class')),
            ],
        ),
        migrations.AddField(
            model_name='instructors',
            name='instructor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User'),
        ),
        migrations.CreateModel(
            name='GroupOne',
            fields=[
                ('key_1', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('eagle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GraderOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grader_ass_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Grader')),
                ('grader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentOne',
            fields=[
                ('key_2', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assignment')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class'),
        ),
    ]
