# Generated by Django 3.0.3 on 2020-04-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0003_assignment_class_eval_set_grader_graderone_question_questionone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class'),
        ),
        migrations.AlterField(
            model_name='assignmentone',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentone',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User'),
        ),
        migrations.AlterField(
            model_name='grader',
            name='assignment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assignment'),
        ),
        migrations.AlterField(
            model_name='graderone',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Grader'),
        ),
        migrations.AlterField(
            model_name='graderone',
            name='grader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User'),
        ),
        migrations.AlterField(
            model_name='groupone',
            name='eagle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.User'),
        ),
        migrations.AlterField(
            model_name='groupone',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group'),
        ),
        migrations.AlterField(
            model_name='questionone',
            name='qset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Assignment'),
        ),
        migrations.AlterField(
            model_name='questionone',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Question'),
        ),
    ]
