# Generated by Django 3.0.3 on 2020-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0003_auto_20200418_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='20097514', max_length=100),
        ),
    ]
