# Generated by Django 3.0.3 on 2020-04-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0004_auto_20200417_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grader',
            name='eval_set_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Eval_set'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='89824622', max_length=100),
        ),
    ]
