# Generated by Django 3.0.3 on 2020-04-19 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0004_auto_20200418_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grader',
            name='eval_set_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.AddField(
            model_name='grader',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='class_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='peer_assessment.Class'),
        ),
        migrations.AddField(
            model_name='questionone',
            name='comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='questionone',
            name='grade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='38157747', max_length=100),
        ),
        migrations.DeleteModel(
            name='Eval_set',
        ),
    ]
