# Generated by Django 3.0.4 on 2020-04-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0005_auto_20200418_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentone',
            old_name='key_2',
            new_name='assignment_one_id',
        ),
        migrations.RenameField(
            model_name='groupone',
            old_name='key_1',
            new_name='group_one_id',
        ),
        migrations.RenameField(
            model_name='instructorset',
            old_name='key_id',
            new_name='instructor_set_id',
        ),
        migrations.RenameField(
            model_name='questionone',
            old_name='key_3',
            new_name='question_one_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='qset_id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grader',
            name='grader_ass_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='66902302', max_length=100),
        ),
    ]
