# Generated by Django 3.0.4 on 2020-04-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0006_auto_20200419_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='91446896', max_length=100),
        ),
    ]
