# Generated by Django 3.0.4 on 2020-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0007_auto_20200419_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='52343983', max_length=100),
        ),
    ]
