# Generated by Django 3.0.4 on 2020-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0009_auto_20200422_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='34158356', max_length=100),
        ),
    ]
