# Generated by Django 3.0.6 on 2020-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assessment', '0013_auto_20200502_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='99843385', max_length=100),
        ),
    ]
